### Pair Programming Numpy

In [1]:
import numpy as np

**Creación y Indexación:**

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [2]:
array1=np.random.randint(10, 100, 50)
print(f'El array1 es:\n{array1}')

print(f'Los elementos en posiciones múltiplo de 5 son:\n{array1[::5]}')

El array1 es:
[40 71 90 55 94 18 19 64 78 33 92 70 84 72 36 14 11 26 69 47 19 46 23 26
 76 85 76 12 14 28 40 15 44 72 32 92 97 17 43 79 80 65 39 34 36 81 33 50
 50 96]
Los elementos en posiciones múltiplo de 5 son:
[40 18 92 14 19 85 40 92 80 81]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [3]:
array2=np.random.randint(1, 21, 30)
print(f'El array2 es:\n{array2}')

print(f'Los elementos en posiciones impares son:\n{array2[1::2]}')

El array2 es:
[ 4 11  9  4  2 19 14 11 10  8  3  2  5  1  7  9 16 20 13  5 16 16 12  7
  9  5  6 19 11 12]
Los elementos en posiciones impares son:
[11  4 19 11  8  2  1  9 20  5 16  7  5 19 12]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [4]:
array3=np.round(np.random.random((4,6))*90,2) #*90 escala los valores para que estén en el rango de 0 a 90
print(f'El array3 es:\n{array3}\n')

print(f'La última fila del array3 es:\n{array3[-1]}')

El array3 es:
[[79.38 77.72 51.97 29.3  35.74 30.69]
 [31.3  84.51 16.26 78.3  30.88 44.16]
 [63.4  76.15 88.56 87.34 54.59  5.91]
 [52.99 22.69 39.58 32.39 47.89 11.16]]

La última fila del array3 es:
[52.99 22.69 39.58 32.39 47.89 11.16]


4. **BONUS:** Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [7]:
#Creo el array 3D
array3d=np.random.randint(0,101, (2,3,5))
print(f'El array 3D original es:\n{array3d}')

#Aplano el array para facilitar el acceso a los índices
array3dmod=array3d.flatten()

#Reemplazo los elementos en posiciones múltiplos de 3, por 0
array3dmod[::3]=0

#Reconstruyo el array 3D con los valores del aplanado
array3d=array3dmod.reshape((2,3,5))
print(f'\nEl array 3D modificado es:\n{array3d}')

El array 3D original es:
[[[ 13  88  71  81  90]
  [ 63  82  81  21  74]
  [100  21  53  82  57]]

 [[ 35  67  79  35  53]
  [ 81  40  95  96  91]
  [ 14   3  62  16  22]]]

El array 3D modificado es:
[[[  0  88  71   0  90]
  [ 63   0  81  21   0]
  [100  21   0  82  57]]

 [[  0  67  79   0  53]
  [ 81   0  95  96   0]
  [ 14   3   0  16  22]]]


**Reshape y Transpose:**

##### Ejercicios con reshape:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [9]:
#Creo el array 3D
array3d_new=np.random.randint(1,101, (2,3,4)) #2*3*4=24 elementos
print(f'El array original es:\n{array3d_new}')

#Creo array 2D de 24 para que tenga la misma cantidad de elementos que el original
array2d=array3d_new.reshape(6,4)
print(f'\nEl array 2D es:\n{array2d}')

El array original es:
[[[ 4 43 74 82]
  [26 15 88  8]
  [ 1 79 93 83]]

 [[43 34 21 47]
  [80 24  5 49]
  [ 6 41 43 69]]]

El array 2D es:
[[ 4 43 74 82]
 [26 15 88  8]
 [ 1 79 93 83]
 [43 34 21 47]
 [80 24  5 49]
 [ 6 41 43 69]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [11]:
#Utilizo arange porque el total de elementos será 60 y quiero que sean secuenciales
array3d_last=np.arange(1,61).reshape(3,4,5) #Le pongo reshape porque con un arange no puedo especificar la forma
print(f'El array original es:\n{array3d_last}')

#Lo convierto a 2D
array2d_last=array3d_last.reshape(12,5)
print(f'\nEl nuevo array es:\n{array2d_last}')

El array original es:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

El nuevo array es:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]


##### Ejercicios con transpose:

3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [13]:
#0=arrays, 1=filas, 2=columnas
#El array original tenía una forma (3,4,5)
print(f'El array original era:\n{array3d_last}')

#El nuevo array tiene forma (5,4,3)
#Lo transpongo con (2,1,0) porque el 2 son columnas (eran 5), el 1 son filas (eran 4), el 0 son ejes (eran 3)
#La posición antes 0 ahora es la última, la posición 1 sigue siendo la 1, la posición 2 ahora es la primera --> (2,1,0)
array_trans=array3d_last.transpose(2,1,0)
print(f'\nEl nuevo array es:\n{array_trans}')

El array original era:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

El nuevo array es:
[[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 60]]]


4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [14]:
#0=arrays, 1=filas, 2=columnas
#El array original tenía una forma (3,4,5)
print(f'El array original era:\n{array3d_last}')

#El nuevo array tiene forma (3,5,4)
array_trans_new=array3d_last.transpose(0,2,1)
print(f'\nEl nuevo array es:\n{array_trans_new}')

El array original era:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

El nuevo array es:
[[[ 1  6 11 16]
  [ 2  7 12 17]
  [ 3  8 13 18]
  [ 4  9 14 19]
  [ 5 10 15 20]]

 [[21 26 31 36]
  [22 27 32 37]
  [23 28 33 38]
  [24 29 34 39]
  [25 30 35 40]]

 [[41 46 51 56]
  [42 47 52 57]
  [43 48 53 58]
  [44 49 54 59]
  [45 50 55 60]]]


##### Preguntas teóricas:

5. ¿Qué diferencia existe entre el reshape y el transpose?

`Reshape` cambia la forma del array pero mantiene el mismo orden.

`Transpose` cambia el orden de los ejes y el contenido se reorganiza según los nuevos ejes.

6. ¿Y entre el transpose y el swapaxes?

`Transpose` permite cualquier permutación de los ejes.

`Swapaxes` sólo intercambia dos ejes del array.

**Funciones Aritméticas y Estadísticas:**

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [15]:
new_3d_array=np.round(np.random.random((2,3,5)),1)
new_3d_array

array([[[0.9, 0.5, 0.2, 0.4, 0.2],
        [0.9, 0.7, 0.2, 0.7, 0.1],
        [0.8, 0.4, 0.1, 0. , 0.1]],

       [[0.1, 1. , 1. , 0.6, 0.8],
        [0.8, 0.8, 0.2, 1. , 0.9],
        [0.5, 0.4, 0.4, 0.2, 1. ]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".

- Si el valor del array es mayor que la media, se reemplaza por "B".

- Si el valor del array es menor que la media, se reemplaza por "C".

- Si el valor es igual que el máximo, se reemplaza por "D".

- Si el valor es igual que el mínimo, se reemplaza por "E".

#a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],

[[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]])

#sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

#nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],

[["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]])

In [24]:
#Creo el array vacío y compruebo shape
empty_3d_array=np.empty((2,3,5))
print(f'La forma del array vacío es: {empty_3d_array.shape}')

#Reemplazo los valores vacíos por los del anterior array
empty_3d_array[:]=new_3d_array
print(f'\nEl array con los datos del anterior es:\n{empty_3d_array}')

La forma del array vacío es: (2, 3, 5)

El array con los datos del anterior es:
[[[0.9 0.5 0.2 0.4 0.2]
  [0.9 0.7 0.2 0.7 0.1]
  [0.8 0.4 0.1 0.  0.1]]

 [[0.1 1.  1.  0.6 0.8]
  [0.8 0.8 0.2 1.  0.9]
  [0.5 0.4 0.4 0.2 1. ]]]


In [25]:
#Calculo las variables para poder aplicar después las condiciones
media=np.mean(new_3d_array)
print(f'La media es: {media}')
maximo=np.max(new_3d_array)
print(f'El máximo es: {maximo}')
minimo=np.min(new_3d_array)
print(f'El mínimo es: {minimo}')

La media es: 0.53
El máximo es: 1.0
El mínimo es: 0.0


In [27]:
#Creo una máscara para cada condición
mask_a=empty_3d_array == media
mask_b=empty_3d_array > media
mask_c=empty_3d_array < media
mask_d=empty_3d_array == maximo
mask_e=empty_3d_array == minimo

In [26]:
#Convierto el array a tipo object para poder añadir letras y mantener los número si fuera necesario
array_object=empty_3d_array.astype(object)

In [28]:
#Reemplazo valores según condiciones
array_object[mask_a]='A'
array_object[mask_b]='B'
array_object[mask_c]='C'
array_object[mask_d]='D'
array_object[mask_d]='D'

In [30]:
#Imprimo array modificado
print(f'El array modificado es:\n{array_object}')

El array modificado es:
[[['B' 'C' 'C' 'C' 'C']
  ['B' 'B' 'C' 'B' 'C']
  ['B' 'C' 'C' 'C' 'C']]

 [['C' 'D' 'D' 'B' 'B']
  ['B' 'B' 'C' 'D' 'B']
  ['C' 'C' 'C' 'C' 'D']]]
